{
 "title": "Tempo / Writes",
 "tags": [ "tempo" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(tempo_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(tempo_build_info{}, namespace)"
   }
  ]
 },
 "panels": [
  {
   "title": "Distributor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Distributors receive spans and forward them to the appropriate ingesters. See [Distributor](https://grafana.com/docs/tempo/latest/configuration/#distributor) for more details on the component."
   }
  },
  {
   "title": "Spans/Second",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_receiver_accepted_spans{}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_receiver_refused_spans{}[$__rate_interval]))",
     "legendFormat": "refused"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 3 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_distributor_push_duration_seconds_bucket{}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 99th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tempo_distributor_push_duration_seconds_bucket{}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 50th"
    },
    {
     "expr": "sum(rate(tempo_distributor_push_duration_seconds_sum{}[$__rate_interval])) by () * 1e3 / sum(rate(tempo_distributor_push_duration_seconds_count{}[$__rate_interval])) by ()",
     "legendFormat": "{{route}} Average"
    }
   ]
  },
  {
   "title": "Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "The ingester is responsible for batching up traces and pushing them to TempoDB. See [Ingester](https://grafana.com/docs/tempo/latest/configuration/#ingester) for more details on the component."
   }
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(tempo_request_duration_seconds_count{route=~'/tempopb.Pusher/Push.*'}[$__rate_interval]),\n  'status', '${1}xx', 'status_code', '([0-9])..'),\n  'status', '${1}', 'status_code', '([a-zA-Z]+)'))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempo_request_duration_seconds_bucket{route=~'/tempopb.Pusher/Push.*'}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 99th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tempo_request_duration_seconds_bucket{route=~'/tempopb.Pusher/Push.*'}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 50th"
    },
    {
     "expr": "sum(rate(tempo_request_duration_seconds_sum{route=~'/tempopb.Pusher/Push.*'}[$__rate_interval])) by () * 1e3 / sum(rate(tempo_request_duration_seconds_count{route=~'/tempopb.Pusher/Push.*'}[$__rate_interval])) by ()",
     "legendFormat": "{{route}} Average"
    }
   ]
  },
  {
   "title": "Backend - Ingester",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(tempodb_backend_request_duration_seconds_count{operation=~'(PUT|POST)'}[$__rate_interval]),\n  'status', '${1}xx', 'status_code', '([0-9])..'),\n  'status', '${1}', 'status_code', '([a-zA-Z]+)'))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempodb_backend_request_duration_seconds_bucket{operation=~'(PUT|POST)'}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 99th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tempodb_backend_request_duration_seconds_bucket{operation=~'(PUT|POST)'}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 50th"
    },
    {
     "expr": "sum(rate(tempodb_backend_request_duration_seconds_sum{operation=~'(PUT|POST)'}[$__rate_interval])) by () * 1e3 / sum(rate(tempodb_backend_request_duration_seconds_count{operation=~'(PUT|POST)'}[$__rate_interval])) by ()",
     "legendFormat": "{{route}} Average"
    }
   ]
  },
  {
   "title": "Backend - Compactor",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 29 },
   "options": {
    "content": "Compactors stream blocks from the storage backend, combine them and write them back. See [Compactor](https://grafana.com/docs/tempo/latest/configuration/#compactor) for more details on the component."
   }
  },
  {
   "title": "QPS",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (status) (\n  label_replace(label_replace(rate(tempodb_backend_request_duration_seconds_count{operation=~'(PUT|POST)'}[$__rate_interval]),\n  'status', '${1}xx', 'status_code', '([0-9])..'),\n  'status', '${1}', 'status_code', '([a-zA-Z]+)'))\n",
     "legendFormat": "{{status}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(tempodb_backend_request_duration_seconds_bucket{operation=~'(PUT|POST)'}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 99th"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(tempodb_backend_request_duration_seconds_bucket{operation=~'(PUT|POST)'}[$__rate_interval])) by (le,)) * 1e3",
     "legendFormat": "{{route}} 50th"
    },
    {
     "expr": "sum(rate(tempodb_backend_request_duration_seconds_sum{operation=~'(PUT|POST)'}[$__rate_interval])) by () * 1e3 / sum(rate(tempodb_backend_request_duration_seconds_count{operation=~'(PUT|POST)'}[$__rate_interval])) by ()",
     "legendFormat": "{{route}} Average"
    }
   ]
  }
 ]
}