{
 "title": "Tempo / Tenants",
 "tags": [ "tempo" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "lokids", "label": "Loki datasource", "query": "loki" },
   { "name": "prometheusds", "label": "Prometheus datasource", "query": "prometheus" },
   {
    "name": "juju_unit",
    "label": "Juju unit",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\",juju_application=~\"$juju_application\"},juju_unit)"
    }
   },
   {
    "name": "juju_application",
    "label": "Juju application",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\",juju_model_uuid=~\"$juju_model_uuid\"},juju_application)"
    }
   },
   {
    "name": "juju_model_uuid",
    "label": "Juju model uuid",
    "query": {
     "query": "label_values(up{juju_model=~\"$juju_model\"},juju_model_uuid)"
    }
   },
   { "name": "juju_model", "label": "Juju model", "query": { "query": "label_values(up,juju_model)" } },
   { "name": "datasource", "label": "Data source", "query": "prometheus" },
   {
    "name": "cluster",
    "label": "cluster",
    "query": "label_values(tempo_build_info, cluster)"
   },
   {
    "name": "namespace",
    "label": "namespace",
    "query": "label_values(tempo_build_info{}, namespace)"
   },
   {
    "name": "tenant",
    "label": "tenant",
    "query": "label_values(tempodb_blocklist_length{}, tenant)"
   }
  ]
 },
 "panels": [
  {
   "title": "Tenant info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
   "options": {
    "content": "Tenant configuration and limits for the specified tenant. "
   }
  },
  {
   "title": "Limits",
   "type": "table-old",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (tempo_limits_overrides{user='$tenant'})\n  or max by (cluster, namespace, limit_name) (tempo_limits_defaults{})\n) by (limit_name)\n"
    }
   ]
  },
  {
   "title": "Ingestion",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 11 },
   "options": {
    "content": "Ingestion statistics for the specified tenant. Look for spikes or gaps in ingestion."
   }
  },
  {
   "title": "Distributor bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_bytes_received_total{tenant='$tenant'}[$__rate_interval]))",
     "legendFormat": "received"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (tempo_limits_overrides{user='$tenant',limit_name='ingestion_rate_limit_bytes'})\n  or max by (cluster, namespace, limit_name) (tempo_limits_defaults{limit_name='ingestion_rate_limit_bytes'})\n) by (ingestion_rate_limit_bytes)\n",
     "legendFormat": "limit"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (tempo_limits_overrides{user='$tenant',limit_name='ingestion_burst_size_bytes'})\n  or max by (cluster, namespace, limit_name) (tempo_limits_defaults{limit_name='ingestion_burst_size_bytes'})\n) by (ingestion_burst_size_bytes)\n",
     "legendFormat": "burst limit"
    }
   ]
  },
  {
   "title": "Distributor spans/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_distributor_spans_received_total{tenant='$tenant'}[$__rate_interval]))",
     "legendFormat": "accepted"
    },
    {
     "expr": "sum(rate(tempo_discarded_spans_total{tenant='$tenant'}[$__rate_interval])) by (reason)",
     "legendFormat": "refused {{ reason }}"
    }
   ]
  },
  {
   "title": "Live traces",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(tempo_ingester_live_traces{tenant='$tenant'})",
     "legendFormat": "live traces"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (tempo_limits_overrides{user='$tenant',limit_name='max_global_traces_per_user'})\n  or max by (cluster, namespace, limit_name) (tempo_limits_defaults{limit_name='max_global_traces_per_user'})\n) by (max_global_traces_per_user)\n",
     "legendFormat": "global limit"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (tempo_limits_overrides{user='$tenant',limit_name='max_local_traces_per_user'})\n  or max by (cluster, namespace, limit_name) (tempo_limits_defaults{limit_name='max_local_traces_per_user'})\n) by (max_local_traces_per_user)\n",
     "legendFormat": "local limit"
    }
   ]
  },
  {
   "title": "Reads",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "Traces data reads for the specified tenant. Look for spikes or gaps in ingestion."
   }
  },
  {
   "title": "Queries/s (ID lookup)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_query_frontend_queries_total{tenant='$tenant',op='traces'}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Queries/s (search)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_query_frontend_queries_total{tenant='$tenant',op='search'}[$__rate_interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
   "options": {
    "content": "Storage data behaviour for the specified tenant."
   }
  },
  {
   "title": "Blockslist length",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "avg(tempodb_blocklist_length{tenant='$tenant'})",
     "legendFormat": "length"
    }
   ]
  },
  {
   "title": "Outstanding compactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tempodb_compaction_outstanding_blocks{tenant='$tenant'})\n/\ncount(tempo_build_info{})\n",
     "legendFormat": "blocks"
    }
   ]
  },
  {
   "title": "Metrics generator",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 },
   "targets": [
    {}
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 41 },
   "options": {
    "content": "Tenant metric generator data. Note that for any data to show up, metrics-generator needs to be show up. See [its documentation](https://grafana.com/docs/tempo/latest/metrics-generator/) for more details on the component."
   }
  },
  {
   "title": "Bytes/s",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(tempo_metrics_generator_bytes_received_total{tenant='$tenant'}[$__rate_interval]))",
     "legendFormat": "rate"
    }
   ]
  },
  {
   "title": "Active series",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(tempo_metrics_generator_registry_active_series{tenant='$tenant'})",
     "legendFormat": "{{ tenant }}"
    },
    {
     "expr": "max(\n  max by (cluster, namespace, limit_name) (tempo_limits_overrides{user='$tenant',limit_name='metrics_generator_max_active_series'})\n  or max by (cluster, namespace, limit_name) (tempo_limits_defaults{limit_name='metrics_generator_max_active_series'})\n) by (metrics_generator_max_active_series)\n",
     "legendFormat": "limit"
    }
   ]
  }
 ]
}