name: Build/Test

on:
  workflow_call:
    secrets:
      CHARMHUB_TOKEN:
        required: true
  pull_request:
    branches:
      - main

jobs:
  lint-qa:
    name: QA - lint + unit
    runs-on: ubuntu-24.04
    # runs-on: ["self-hosted", "linux", "X64", "large", "jammy"]
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4
      - name: Install dependencies
        run: sudo snap install --classic astral-uv
      - name: Run linters
        run: make lint
      - name: Check libs
        uses: canonical/charming-actions/check-libraries@934193396735701141a1decc3613818e412da606 # 2.6.3
        with:
          charmcraft-channel: 3.x/candidate
          credentials: "${{ secrets.CHARMHUB_TOKEN }}"
          github-token: "${{ secrets.GITHUB_TOKEN }}"
      - name: Run tests
        run: make unit

  prepare-itest-runs:
    name: Build charm and testers
    runs-on: ubuntu-24.04
    # runs-on: ["self-hosted", "linux", "X64", "large", "jammy"]
    needs:
      - lint-qa
    outputs:
      suites: ${{ steps.suites.outputs.suites }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install lxd and charmcraft
        run: sudo snap install charmcraft --classic

      - name: Generate dependency files
        run: |
          sudo snap install --classic astral-uv
          make generate-requirements

      - name: Pack charm
        run: charmcraft pack -v

      - name: Pack tester
        run: charmcraft pack -v -p ./tests/integration/tester/

      - name: Pack tester-grpc
        run: charmcraft pack -v -p ./tests/integration/tester-grpc/

      - name: Upload charm artifacts
        uses: actions/upload-artifact@b4b15b8c7c6ac21ea08fcf65892d2ee8f75cf882 # v4
        with:
          name: charms
          if-no-files-found: error
          path: ./*.charm

      - name: Generate matrix list and tasks
        id: suites
        run: |
          python3 ./tests/spread/generate_spread_tasks.py
          list="$(charmcraft test --list github-ci | sed "s|github-ci:ubuntu-24.04:tests/spread/||g" | jq -r -ncR '[inputs | select(length>0)]')"
          echo "suites=$list"
          echo "suites=$list" >> $GITHUB_OUTPUT

  integration-test:
    name: Spread (${{ matrix.suite }})
    runs-on: ubuntu-24.04
    # runs-on: ["self-hosted", "linux", "X64", "large", "jammy"]
    needs:
      - prepare-itest-runs
    strategy:
      fail-fast: false
      matrix:
        suite: ${{ fromJSON(needs.prepare-itest-runs.outputs.suites) }}
    # Allow Juju 3.6 jobs to fail, given that it's in beta
    continue-on-error: ${{ contains(matrix.suite, 'juju_3_6') }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Download charm artifacts
        uses: actions/download-artifact@fa0a91b85d4f404e444e00e005971372dc801d16 # v4
        with:
          name: charms
          path: ./
          merge-multiple: true

      - name: Display CWD contents
        run: ls ./

      - name: Generate matrix list and tasks
        id: suites
        run: |
          python3 ./tests/spread/generate_spread_tasks.py

      - name: Setup LXD
        uses: canonical/setup-lxd@main

      - name: Install charmcraft
        run: sudo snap install charmcraft --classic

      - name: Run integration tests
        run: |
          charmcraft test -v "github-ci:ubuntu-24.04:tests/spread/${{ matrix.suite }}"
