name: Pull Requests

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'CONTRIBUTING.md'
      - 'INTEGRATING.md'
      - 'CODEOWNERS'
      - 'LICENSE'
      - 'icon.svg'
      - '.gitignore'
      - '.github/**'

jobs:
  pull-request:
    name: PR
    uses: canonical/observability/.github/workflows/charm-pull-request.yaml@v0
    secrets: inherit

  terraform-checks:
    name: Terraform
    uses: canonical/observability/.github/workflows/terraform-quality-checks.yaml@v0
